### ISSUE TITLE
Could not find a version that satisfies the requirement torch>=1.7 

### ISSUE THREAD

**Issue by kirbyju** [bowang-lab/MedSAMSlicer#11]
I'm using Slicer 5.7 2024-01-28 preview build on a Macbook M2 Pro with Sonoma 14.3. I saw your extension showed up in the Extension Manager so I tried installing it that way.  It got through the initial install, asked me to restart Slicer, then asked me to download something (I forget what it was).  That seemed to work okay as well.  Then when I got the popup stating this:

`PyTorch will be downloaded and installed using light-the-torch (ltt install torch>=1.7 torchvision>=0.8 --pytorch-computation-backend=cu117). The process might take some minutes.`

Nothing seemed to happen so I checked the log and saw this error:

```
ERROR: Could not find a version that satisfies the requirement torch>=1.7 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0)
ERROR: No matching distribution found for torch>=1.7
```

**Comment by rasakereh** [comment]
Hi, sorry for the late reply. why is it stating that the installation is happening using "light-the-torch" and not pip? Have you tried to install it yourself? AFAIK we use torch==2.0.1 torchvision==0.15.2 and use pip for that. I am not sure how these versions are being installed on your end

**Comment by kirbyju** [comment]
Not sure.  I just clicked the installation button to install your extension via the Slicer extension manager and followed the prompts in the GUI.  I wasn't using pip or light-the-torch or anything else from a command line.
