### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by 111678900** [bowang-lab/MedSAMSlicer#13]
error: Application does NOT exists [D:/A_A05_002 SSCOM 32/Slicer 5.6.1/bin/./python-real.exe]
Usage
  PythonSlicer [options]

I've encountered this questions

**Comment by rasakereh** [comment]
Hi would you please send me a more detailed error message? At what stage do you get this? I assume that it should happen after installing the dependencies but from issue #14 you've submitted I think that you have not completed that step yet
