### ISSUE TITLE
MedSAM lite server

### ISSUE THREAD

**Issue by Guojfeng** [bowang-lab/MedSAMSlicer#17]
Hi, when i  installing the plugin, it running the step of “installing dependencies:MedSAM lite server”  for a long time (about 2 hours),and no error message appear,i reinstall the slicer but can not solve it (slicer 5.6, v.0.05). What should i check out?  hope your reply, thank you!

**Comment by Guojfeng** [comment]
I solve it haha

**Comment by linyueDh** [comment]
> I solve it haha

can you teach me how to solve it?thank you

**Comment by Guojfeng** [comment]
> > I solve it haha
> 
> can you teach me how to solve it?thank you

close your VPN,and then install

**Comment by linyueDh** [comment]
> > > I solve it haha
> > 
> > 
> > can you teach me how to solve it?thank you
> 
> close your VPN,and then install

it's useful！thank you.
