### ISSUE TITLE
The installation stops at the following steps How to solve？

### ISSUE THREAD

**Issue by DevPixel1988** [bowang-lab/MedSAMSlicer#18]
![2024-03-14 19 48 32](https://github.com/bowang-lab/MedSAMSlicer/assets/163414585/cac72e7f-544f-495f-863f-c1c12210b8e4)

**Comment by Guojfeng** [comment]
close your vpn before install

**Comment by BULIBULI501** [comment]
I have the same problem, stuck in this step.

**Comment by rasakereh** [comment]
click the rightmost icon on the toolbar (yellow and blue Python icon). copy the log and send it to me. note that this step is the most time-consuming one and you might want to wait a little longer. 
Plus, network connection issues can be a probable explaination
