### ISSUE TITLE
MedSAMLite1 sample data : brain segmentation quality issue 

### ISSUE THREAD

**Issue by AlDevonIA** [bowang-lab/MedSAMSlicer#21]
Hello,

First, I would like to thank you for sharing your work with us!

I'm trying to segment the brain (only the cerebral hemispheres) in the MedSAMLite1 sample data, but the result is not really satisfying as you can see in the screenshot.
I applied the preprocess for MR Images here, but I cannot get any usable results with or without selecting preprocessing options.

So maybe:
- My ROI box is not drawn as it should be to reach a good result (I have tried several drawings though)
- I should preprocess differently the data
- The MedSAMLite1 sample data is not ideal for brain segmentation
- It might be out of the scope of the model
- Something else?

3D Slicer version: 5.6.1
MedSAMSllicer version: 0.05
 

![Capture d'écran 2024-03-21 135855](https://github.com/bowang-lab/MedSAMSlicer/assets/96240751/d841fcec-3dae-4166-b0ab-7270b7c25c0f)

**Comment by dieterrosch** [comment]
I have a similar issue with my own CT scans. I haven't had time to look deeply into it, but I think it has something to do with the origin of CT's not always being in the same place. It's as if the bounding box's top left and bottom right coordinates are wrong way around sometimes. Perhaps it has to do with the CT scanner brand, or the way the scan is done.

What I'm seeing is that the segmentation doesn't run in the area where I put my bounding box. If I put my bounding box on the right side of the slice, it segments areas on the left, and vice versa.

**Comment by JunMa11** [comment]
This issue has been addressed here: https://github.com/bowang-lab/MedSAM/issues/227
