### ISSUE TITLE
The format of images

### ISSUE THREAD

**Issue by liuzh-buaa** [bowang-lab/MedSAMSlicer#23]
I am using [3D Slicer Plugin](https://github.com/bowang-lab/MedSAMSlicer) in 3D Slicer. I notice that the format of images in your paper is 'NifTI', but mine is 'dicom'. I wonder if there are any limitations to the format of images. I am confused about the splitting performance now.

**Comment by rasakereh** [comment]
We have tried dicom images with no problem.
Technical details: Slicer provides us with a numpy array to work with which represents the image. So the algorithm would be format-agnostic
