### ISSUE TITLE
Unable to utilize CUDA cores for computations in 3D Slicer with medSAMslicer

### ISSUE THREAD

**Issue by tnl-o** [bowang-lab/MedSAMSlicer#31]
I am using 3D Slicer 5.6.2 in conjunction with medSAMslicer 0.6. When I click "Send Image" for computations, the process utilizes CPU cores. However, I would like to leverage the power of CUDA cores for faster computations.

**Steps to reproduce:**
Install 3D Slicer 5.6.2 and medSAMslicer 0.6.
Load an image in 3D Slicer.
Click "Send Image" to initiate computations.
Observe that computations are performed using CPU cores.

**Expected behavior:**
The computations should utilize CUDA cores, allowing for faster processing.

**System configuration:**
3D Slicer version: 5.6.2
medSAMslicer version: 0.6
Operating System: Windows 10 Pro 22H2 19045.4651
GPU: NVIDIA GeForce RTX 3060
CUDA version: NVIDIA CUDA 12.6.41 driver

Please let me know if there are any specific settings or configurations I need to adjust to enable CUDA core utilization.

**Comment by rasakereh** [comment]
(The latest release)[https://github.com/bowang-lab/MedSAMSlicer/releases/tag/v0.11] tried to address this issue along with a handful of interesting new features. Can you try it out and lmk if it is fixed on your end?
