### ISSUE TITLE
failed to use 3D Slicer plugin.

### ISSUE THREAD

**Issue by pangshumao** [bowang-lab/MedSAMSlicer#35]
Hi, I installed the MedSAM2 but failed to use the 3D Slicer plugin. I would appreciate you if you can help me to solve it. The installation and usage steps are as follows:

1. SAM2 installation.

step 1. Download the MedSAMSlicer-SAM2.zip to directory /mnt/nas/pangshumao/software at https://github.com/bowang-lab/MedSAMSlicer/tree/SAM2, and unzip the MedSAMSlicer-SAM2.zip.

step 2. Create a virtual environment.
conda create --name SAM2 python=3.11
conda activate SAM2

step3. Install the package.
cd MedSAMSlicer-SAM2
pip install -e .

step 4. Download checkpoints.
cd checkpoints
./download_ckpts.sh

step 5. Run the backend.
cd ../
python server.py

2. 3D Slicer usage.

step 1. Open the 3D Slicer on the server.
Slicer

step 2. Open extension wizard on the 3D Slicer UI.

step 3. Select plugin directory.
Click the Select Extension button, and select the /mnt/nas/pangshumao/software/MedSAMSlicer-SAM2/slicer/SAM2 as plugin directory.

step 4. Open a nifti MR image by 3D Slicer, and switch the Modules to Segmentation->SAM2.

step 5. Set the IP Address and Port to 192.168.10.103 and 8080 respectively.

step 6. Set the Preprocessing Options to MR, and click the Apply buttion.

step 7. Set the ROI.

step 8. Set the Model Size to small, and click Segment Middle Slice button.

The following errors appeared in the backend:

(SAM2) pangshumao@A6000:/mnt/nas/pangshumao/software/MedSAMSlicer-SAM2$ python server.py
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.10.103:8080
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 227-503-081
192.168.10.103 - - [30/Aug/2024 09:50:33] "POST /upload HTTP/1.1" 200 -
192.168.10.103 - - [30/Aug/2024 09:50:38] "POST /run_script HTTP/1.1" 200 -
192.168.10.103 - - [30/Aug/2024 09:50:38] "GET /download_file HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/MedSAMSlicer-SAM2/server.py", line 42, in download_file
    return send_file(output_name, as_attachment=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/flask/helpers.py", line 499, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/werkzeug/utils.py", line 428, in send_file
    stat = os.stat(path)
           ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nas/pangshumao/software/MedSAMSlicer-SAM2/data/video/segs_tiny/img_data.npz'

The following errors appeared in 3D Slicer.

(SAM2) pangshumao@A6000:~$ Slicer
Switch to module:  "Welcome"
Switch to module:  "SAM2"
"Volume" Reader has successfully read the file "/mnt/nas/pangshumao/data/Spine_Segmentation_3D_Space/L4-L5/In/Nii/MR/case1.nii.gz" "[0.20s]"
[-103.30268730240817, None]
[-103.30268730240817, -85.70268704014784]
data sent is:  {'checkpoint': 'small', 'input': 'img_data.npz', 'gts': 'X', 'propagate': 'N'}
Traceback (most recent call last):
  File "/mnt/nas/pangshumao/software/Slicer-5.6.2-linux-amd64/lib/Python/lib/python3.9/site-packages/numpy/lib/npyio.py", line 465, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '<'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/nas/pangshumao/software/MedSAMSlicer-SAM2/slicer/SAM2/SAM2/SAM2.py", line 484, in getMiddleMask
    segmentation_mask = np.load(result_path, allow_pickle=True)['segs']
  File "/mnt/nas/pangshumao/software/Slicer-5.6.2-linux-amd64/lib/Python/lib/python3.9/site-packages/numpy/lib/npyio.py", line 467, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '/tmp/tmp7u7qxq94/result.npz' as a pickle

Note that the SAM2 and 3D Slicer 5.6.2 were installed in the same server which has 4 A6000 GPUs.

**Comment by yiyouyachuming** [comment]
I had a similar problem
File "/mnt/nas/pangshumao/software/anaconda3/envs/SAM2/lib/python3.11/site-packages/werkzeug/utils.py", line 428, in send_file
stat = os.stat(path)
^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nas/pangshumao/software/MedSAMSlicer-SAM2/data/video/segs_tiny/img_data.npz'

**Comment by rasakereh** [comment]
Thanks for sharing the issue. Would you please run the following command and share the output with me?

`python infer_video_tiny_debug.py --img_path 'img_data.npz' --gts_path X --propagate N --checkpoint small`

**Comment by pangshumao** [comment]
> Thanks for sharing the issue. Would you please run the following command and share the output with me?
> 
> `python infer_video_tiny_debug.py --img_path 'img_data.npz' --gts_path X --propagate N --checkpoint tiny`

Hi, the aforementioned command caused the following errors:
UserWarning: Flash attention kernel not used because: (Triggered internally at ../aten/src/ATen/native/transformers/cuda/sdp_utils.cpp:720.)
RuntimeError: No available kernel. Aborting execution.

I solved the aforementioned issue by modifying MedSAMSlicer-SAM2/sam2/modeling/sam/transformer.py as follows:
1. remove the following sentence: 
OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
2. add the following sentence:
USE_FLASH_ATTN = False
MATH_KERNEL_ON = True
OLD_GPU = True

After that, SAM2 and 3D Slicer plugin can work. Thank you for your help.
