### ISSUE TITLE
issue with checkpoint download

### ISSUE THREAD

**Issue by mehrnia** [bowang-lab/MedSAMSlicer#36]
[https://dl.fbaipublicfiles.com/segment_anything_2/072824/](javascript:void(0);)

actually when I run ./download_[ckpts.sh](javascript:void(0);), nothing happens
![image](https://github.com/user-attachments/assets/e5f3fea4-484c-47f7-8942-260a1cf52d0f)
![Capture](https://github.com/user-attachments/assets/20ec0d4e-10f4-41d6-90af-d679ba2153e5)

**Comment by rasakereh** [comment]
It seems that you are using powershell while this is a bash script. You can download the file found [here](https://github.com/bowang-lab/MedSAMSlicer/blob/SAM2/checkpoints/download_checkpoints.ps1) to the same directory and use the following command:
```powershell -ExecutionPolicy Bypass -File .\download_checkpoints.ps1```

I noticed that powershell download can sometimes be slow. So you can alternatively download your desired checkpoints manually using the following urls:
https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt
https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_small.pt
https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_base_plus.pt
https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt

The first one is usually enough.

**Comment by mehrnia** [comment]
Thank you I actually I did it.
