### ISSUE TITLE
Problem of install and using SAM2 slicer plug-in

### ISSUE THREAD

**Issue by huanaih11** [bowang-lab/MedSAMSlicer#45]
python infer_video_tiny_debug.py --img_path 'img_data.npz' --gts_path X --propagate N --checkpoint tiny

When I'm running this it reply:
python infer_video_tiny_debug.py --img_path 'img_data.npz' --gts_path X --propagate N --checkpoint tiny
["'img_data.npz'"]
0it [00:00, ?it/s]infering 'img_data.npz'
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\huanai\MedSAMSlicer\infer_video_tiny_debug.py", line 300, in <module>
    infer_3d(img_npz_file, gts_file, propagate)
  File "C:\Users\huanai\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huanai\MedSAMSlicer\infer_video_tiny_debug.py", line 207, in infer_3d
    npz_data = np.load(img_npz_file, 'r', allow_pickle=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huanai\AppData\Roaming\Python\Python311\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "'img_data.npz'"

I followed step-by-step of install videos, can you please help me to solve this problem?
I have no idea how to fix it.

**Comment by rasakereh** [comment]
SAM2 development is discontinued and MedSAM2 has replaced it. Can you try with this version and let me know if the problem is still there.
Link: [https://github.com/bowang-lab/MedSAMSlicer/tree/MedSAM2](https://github.com/bowang-lab/MedSAMSlicer/tree/MedSAM2)

**Make sure that you are using a clean workspace for installation to prevent collisions with SAM2**

**Comment by huanaih11** [comment]
Thank you for your reply.

For the new one, when I want to download the checkpoints, it shows:
Invoke-WebRequest : 未能找到路径“C:\MedSAMSlicer\checkpoints\2.1\sam2_hiera_tiny.pt”的一部分。
所在位置 C:\MedSAMSlicer\extra_files.ps1:10 字符: 1
+ Invoke-WebRequest -Uri $sam2_hiera_t_url -OutFile "checkpoints\2.1\sa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestComma
   nd

Downloading sam2_hiera_small.pt checkpoint...
Invoke-WebRequest : 未能找到路径“C:\MedSAMSlicer\checkpoints\2.1\sam2_hiera_small.pt”的一部分。
所在位置 C:\MedSAMSlicer\extra_files.ps1:13 字符: 1                                                                     + Invoke-WebRequest -Uri $sam2_hiera_s_url -OutFile "checkpoints\2.1\sa ...                                             + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException                             + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestComma
   nd

Downloading sam2_hiera_base_plus.pt checkpoint...
Invoke-WebRequest : 未能找到路径“C:\MedSAMSlicer\checkpoints\2.1\sam2_hiera_base_plus.pt”的一部分。
所在位置 C:\MedSAMSlicer\extra_files.ps1:16 字符: 1
+ Invoke-WebRequest -Uri $sam2_hiera_b_plus_url -OutFile "checkpoints\2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestComma
   nd

Downloading sam2_hiera_large.pt checkpoint...
Invoke-WebRequest : 未能找到路径“C:\MedSAMSlicer\checkpoints\2.1\sam2_hiera_large.pt”的一部分。
所在位置 C:\MedSAMSlicer\extra_files.ps1:19 字符: 1
+ Invoke-WebRequest -Uri $sam2_hiera_l_url -OutFile "checkpoints\2.1\sa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.InvokeWebRequestComma
   nd

All checkpoints are downloaded successfully.
Downloading config files...
Config files downloaded successfully.


And from previous step also showed one error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.9.1.post1 requires python-dateutil>=2.7, which is not installed.

**Comment by rasakereh** [comment]
For first problem, create a directory called `checkpoints` at the root directory. it should resolve the problem

For requirements start from a clean environment and run pip with this flag `pip install --no-cache-dir -r requirements.txt` so it doesn't use cached version. if it didnt work, just remove the line related to `matplotlib` at `requirements.txt` it is optional dep afaik.
