### ISSUE TITLE
MedSAM2 is not setting up Spatial Information

### ISSUE THREAD

**Issue by morganrcu** [bowang-lab/MedSAMSlicer#47]
Hi,
I'm testing MedSAM2 version on the segmentation of a brain tumor and I suspect there is some issue with how MedSAM2 processes origin and spacing information.  I want to segment this bright structure:

![schwannoma](https://github.com/user-attachments/assets/ca0822ab-638c-40e4-b953-2fc0503f409c)

I mark first and last slides and draw a ROI:
![roi](https://github.com/user-attachments/assets/6ac53be8-3307-49cb-a1d9-3a227f234928)

After segmenting middle slice, the result I obtain is on a different slice, shifted and is bigger than expected:
![output](https://github.com/user-attachments/assets/36b1e99c-6f77-4f2d-bd47-8dc9d21cd159)

However, it has a nice shape. My feeling is that the origin and spacing information is not being properly setup on SAM2 output. These are the properties of the MRI volume:

![imagen](https://github.com/user-attachments/assets/99000eb6-5d1e-4633-a194-f43739bb53f7)

Here is the sample data:

https://drive.google.com/file/d/1DUV5wg5fPr8Hkj6MHNnSjsyrCD5TfWXn/view?usp=sharing

Do you think is an spatial metadata issue?
Kind regards,
Rodrigo

**Comment by rasakereh** [comment]
Thank you for bringing this to my attention. It was an issue with index offsetting which is fixed now!
