### ISSUE TITLE
More interaction possible?

### ISSUE THREAD

**Issue by adelka-m** [bowang-lab/MedSAMSlicer#48]
Hi all!
First of all, thank you for the plugin!

I want to use video-SAM for segmenting "super small" structures, e.g. arteries. However,  I did not find it possible yet with the slicer plugin. 

The first problem I am encountering is that when I put the ROI around the artery and push the "segment middle slice" the output does not produces any segmentation. When I then try to "refine middle segmentation", I have to add a new segment. However, this segment is then not taken in account for the "full segmentation" because it does not have the correct name.  (The segments for the plugin have a name like "segment_1_1732558240")

Another interesting feature would be refining the segmentation over multiple slices. Now, if one is not happy with the "full segmentation", you cannot run it again. So you cannot add more segmentations in  other slices which would help the model to get a better segmentation.

Do you plan on adding these features? Or could you hint me how could I adjust your plugin code to my needs?

Thanks a lot!

**Comment by rasakereh** [comment]
Thank you for reaching out! Have you tried the latest MedSAM2 push? I've added the capability of interactive modification using "add segmentation" point and "subtract segmentation" point. Regarding your first issue, can I have a sample file to reproduce the situation?
