### ISSUE TITLE
Issue loading the UI after installation

### ISSUE THREAD

**Issue by stefhec** [bowang-lab/MedSAMSlicer#5]
I am very excited to test MedSAM out through 3D slicer. I finished the installation on my Mac, but run into an issue when loading the UI through "Segmentation --> MedSAMLite". 

I get the following error message:
self.parameterNodeGuiTag = self._parameterNode.connectGui(self.ui)
AttributeError: "MedSAMLiteWidget' object has no attribute 'ui'

Any idea how to resolve this? 

Thanks

**Comment by rasakereh** [comment]
Thank you for sharing your experience. I believe that this error message can be ignored. Unless you are experiencing any issue with UI itself. Are you?

**Comment by stefhec** [comment]
I just noticed there is a new release, which I installed. It works well so far on my Mac. Thank you!
