### ISSUE TITLE
Wrong about python infer_video_tiny_debug.py --img_path 'img_data.npz' --gts_path X --propagate N --checkpoint tiny

### ISSUE THREAD

**Issue by GuMercury** [bowang-lab/MedSAMSlicer#52]
the wrong is:
RuntimeError: No available kernel. Aborting execution.
But server's gpu is available.
TY.

**Comment by GuMercury** [comment]
my gpus are 4*3090.Do my gpus have enough memory usage?

**Comment by rasakereh** [comment]
i updated the sanity check, would you try again?

**Comment by GuMercury** [comment]
Thank you for reply. This question is fixed.
