### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by wicky-dot** [bowang-lab/MedSAMSlicer#7]
I repeatedly encounter timeout errors when installing dependency packages. Are there any other ways to install dependencies?
![image](https://github.com/bowang-lab/MedSAMSlicer/assets/62839062/e83176a7-1db0-4237-a413-bb2f009d7264)

**Comment by rasakereh** [comment]
Thank you for reporting the problem. This is the file that our app tries to download: [https://github.com/rasakereh/medsam-3dslicer/raw/master/server_essentials.zip](https://github.com/rasakereh/medsam-3dslicer/raw/master/server_essentials.zip)
 Can you access it with no proxy, etc using your browser?
Currently, the only way to install dependencies is through the module. We will fix this in future.

**Comment by wicky-dot** [comment]
I am able to locate the "server_essentials.zip" file in the previous downloaded medsam folder. What should I do next?
![image](https://github.com/bowang-lab/MedSAMSlicer/assets/62839062/5112f619-4022-4c5b-9fa1-e639ac800e66)

**Comment by rasakereh** [comment]
We have a new [release](https://github.com/bowang-lab/MedSAMSlicer/releases/tag/v0.03) that might work fine for you. 
In this release, we added the functionality to use a local `server_essentials.zip` file to install dependencies. You just check the box and select this zip file. Hopefully it fixes the issue.

**Comment by wicky-dot** [comment]
Thank you so much! The issue has been solved!
