### ISSUE TITLE
Pytorch with cuda support

### ISSUE THREAD

**Issue by Enzo-Kerkhof** [bowang-lab/MedSAMSlicer#8]
Hi, as far as I can tell Total Segmentator and MedSAM use the same pytorch version. If you already have TS installed in your slicer instance this conflicts with a MedSAM install since the MedSAM extension requires the non-cuda version of Pytorch 2.0.1

Force reinstalling the cuda version of Pytorch using the pytorch install extension made the GUI of MedSAM ask for dependencies again. Can this be solved easily?

**Comment by rasakereh** [comment]
Thank you, it is actually a good point that I haven't thought about before. We consider our options and keep you posted

**Comment by Enzo-Kerkhof** [comment]
In the new version v0.04 this issue is solved.
@rasakereh thanks a lot!
